### ISSUE TITLE
Examples no longer load data.

### ISSUE THREAD

**Issue by grechaw** [marklogic/entity-services#196]
The .flush method went away on batcher, so I removed invocations from the examples loading code, but now something is missing because the data never gets loaded from sources.  

I need to reinstate whatever new code replaces the old flush method.

**Comment by grechaw** [comment]
The replacement method is flushAsync or flushAndWait.  I need to reincorporate one of these into each example.

**Comment by grechaw** [comment]
I went ahead and resolved this little issue with examples and pushed.  examples now should be working well with current develop branch of java client.

**Comment by bsrikan** [comment]
@grechaw When I run "../gradlew runExampleRaces" I get transform extension does not exist error:

```
ERROR c.m.e.e.ExamplesBase - FAILURE on batch:com.marklogic.client.datamovement.impl.WriteBatchImpl@592202

com.marklogic.client.FailedRequestException: Local message: failed to apply resource at documents: Bad Request. Server Message: RESTAPI-INVALIDREQ: (err:FOER0000) Invalid request:  reason: transform extension does not exist: turtle-to-xml
Local message: failed to apply resource at documents: Bad Request. Server Message: RESTAPI-INVALIDREQ: (err:FOER0000) Invalid request:  reason: transform extension does not exist: turtle-to-xml
        at com.marklogic.client.impl.JerseyServices.checkStatus(JerseyServices.java:4231)
        at com.marklogic.client.impl.JerseyServices.postResource(JerseyServices.java:3242)
        at com.marklogic.client.impl.JerseyServices.postBulkDocuments(JerseyServices.java:3330)
        at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:618)
        at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
        at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:611)
        at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
        at com.marklogic.client.datamovement.impl.WriteBatcherImpl$BatchWriter.run(WriteBatcherImpl.java:917)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

```
ERROR c.m.e.e.r.Harmonizer - FAILURE on batch:com.marklogic.client.datamovement.impl.QueryBatchImpl@67746e46

com.marklogic.client.FailedRequestException: Local message: failed to apply resource at internal/apply-transform: Bad Request. Server Message: RESTAPI-INVALIDREQ: (err:FOER0000) Invalid request:  reason: transform extension does not exist: ingester-angel-island
        at com.marklogic.client.impl.JerseyServices.checkStatus(JerseyServices.java:4231)
        at com.marklogic.client.impl.JerseyServices.postResource(JerseyServices.java:3156)
        at com.marklogic.client.impl.JerseyServices.postResource(JerseyServices.java:3110)
        at com.marklogic.client.datamovement.ApplyTransformListener.processEvent(ApplyTransformListener.java:93)
        at com.marklogic.client.datamovement.impl.QueryBatcherImpl$QueryTask.run(QueryBatcherImpl.java:412)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by bsrikan** [comment]
I did install the latest java-client snapshot like so:
`mvn install:install-file -DgroupId=com.marklogic -DartifactId=java-client-api -Dpackaging=jar -Dversion=4.0-SNAPSHOT -Dfile='lib/java-client-api-4.0-SNAPSHOT.jar'`
and could see in my Eclipse that import statements for WriteBatcher and QueryBatcher do resolve.

**Comment by grechaw** [comment]
runExample must be run after mlDeploy.

**Comment by bsrikan** [comment]
This is now fixed. To deploy races have to deploy as:
../gradlew -PexampleDir=example-races mlDeploy

to run races example:
../gradlew runExampleRaces

Shipping the bug as examples loads data as expected.
