### ISSUE TITLE
Update/add e2e test for 9.0-3

### ISSUE THREAD

**Issue by bsrikan** [marklogic/entity-services#334]
This task is to track e2e updates and new test queries that has to be added for enhancements in 9.0-3.

Subscribing @grechaw

**Comment by bsrikan** [comment]
Working on granular privileges test most of this week. Will get to e2e the week after.

**Comment by bsrikan** [comment]
Updated all the artefacts in e2e with the latest code.
mldeploy gives an error as so @grechaw :

```
entity-services-e2e$ ./gradlew mldeploy
:entity-services-e2e:mlDeleteModuleTimestampsFile
Deleting /Users/sbalasub/git/entity-services/entity-services-e2e/build/ml-last-configured-timestamps.properties

:entity-services-e2e:mlPrepareRestApiDependencies
:entity-services-e2e:mlDeployApp
Exception in thread "ThreadPoolTaskExecutor-2" com.marklogic.client.FailedRequestException: Local message: /config/query write failed: Bad Request. Server Message: RESTAPI-INVALIDCONTENT: (err:FOER0000) Invalid content: Operation results in invalid Options: XDMP-VALIDATEMISSINGATTR: (err:XQDY0027) validate strict { $opt } -- Missing required attribute: Found () but required (@name & @ns?) at fn:doc("")/search:options/search:constraint[6]/search:range/search:element using schema "search.xsd"()(@name & @ns?)fn:doc("")/search:options/search:constraint[6]/search:range/search:element"search.xsd"
        at com.marklogic.client.impl.JerseyServices.putPostValueImpl(JerseyServices.java:3014)
        at com.marklogic.client.impl.JerseyServices.putValue(JerseyServices.java:2865)
        at com.marklogic.client.impl.QueryOptionsManagerImpl.writeOptions(QueryOptionsManagerImpl.java:158)
        at com.marklogic.client.modulesloader.impl.DefaultModulesLoader$3.run(DefaultModulesLoader.java:522)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
:entity-services-e2e:mlPostDeploy UP-TO-DATE
:entity-services-e2e:mlDeploy
```

**Comment by bsrikan** [comment]
Above mentioned issue is now fixed. Created a PR with updates to e2e with 9.0-3 enhancements.
validation of superstore envelope against entity-type.xsd gave an error and so did deploying generated search options with namespace in it. Both the issues #313 and #343 assigned to Charles for further analysis.

**Comment by bsrikan** [comment]
Able to deploy e2e now and both 313 and 343 have been shipped. Made significant progress in e2e.
Generated a new project to test models with namespace as part of 9.0-3 enhancements. Generated new artifacts updated both e2e-nwind and e2e-namespace project. e2e-nwind is already checked in with latest artefacts. 

Verified that extract-instance, canonical data and envelopes work fine in the namespace project. Will work on queries so tde, search-options and database properties are tested. Then add them all to qc-workspace and add a test in regression.

**Comment by bsrikan** [comment]
Checked in e2e-nwind updates in a PR. Have another set of checkins ready for namespaces. Facing some concerns with translate and upconverts. Will discuss with Charles tomorrow and resolve.  It could either be issue which has to be triaged or an expected behavior. Whatever the conclusion, post discussion I will be able to checkin my changes for namespace e2e test tomorrow and ship this task.

**Comment by bsrikan** [comment]
With PR #350 all planned e2e tests are in. This task is good to ship.
